version: 2.1

orbs:
  win: circleci/windows@2.4.0

defaults: &defaults
  parameters:
    maven_version:
      type: string
      default: ""
    jdk_version:
      type: string
      default: ""
    node_version:
      type: string
      default: ""
  working_directory: ~/snyk-mvn-plugin

windows_defaults: &windows_defaults
  environment:
    npm_config_loglevel: silent
  executor:
    name: win/default

commands:
  install_deps:
    description: Install dependencies
    steps:
      - run:
          name: Install dependencies
          command: npm install
  install_node_npm:
    description: Install correct Node version
    parameters:
      node_version:
        type: string
        default: ""
    steps:
      - run:
          name: Install correct version of Node
          command: nvm install << parameters.node_version >>
      - run:
          name: Use correct version of Node
          command: nvm use << parameters.node_version >>
  show_node_version:
    description: Log Node and npm version
    steps:
      - run:
          name: Node version
          command: node --version
      - run:
          name: NPM version
          command: npm --version
  install_sdkman:
    description: Install SDKMAN
    steps:
      - run:
          name: Installing SDKMAN
          command: |
            curl -s "https://get.sdkman.io?rcupdate=false" | bash
            echo -e '\nsource "/home/circleci/.sdkman/bin/sdkman-init.sh"' >> $BASH_ENV
            source $BASH_ENV
  install_jdk_unix:
    description: Install JDK
    parameters:
      jdk_version:
        type: string
        default: ""
    steps:
      - run:
          name: Installing JDK
          command: sdk install java $(sdk list java | grep -o -m1 "<< parameters.jdk_version >>\.[0-9\.]\+hs-adpt")
  install_jdk_windows:
    description: Install JDK
    parameters:
      jdk_version:
        type: string
        default: ""
    steps:
      - run:
          name: Installing JDK
          command: choco install openjdk
  install_maven_unix:
    description: Install maven
    parameters:
      maven_version:
        type: string
        default: ""
    steps:
      - run:
          name: Installing Maven
          command: sdk install maven << parameters.maven_version >>
  install_maven_windows:
    description: Install maven
    parameters:
      maven_version:
        type: string
        default: ""
    steps:
      - run: choco install maven --version=<< parameters.maven_version >>

jobs:
  lint:
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    steps:
      - checkout
      - install_deps
      - show_node_version
      - run:
          name: Run lint
          command: npm run lint

  test-windows:
    <<: *defaults
    <<: *windows_defaults
    steps:
      - run: git config --global core.autocrlf false
      - checkout
      - install_node_npm:
          node_version: << parameters.node_version >>
      - install_jdk_windows
      - install_maven_windows:
          maven_version: << parameters.maven_version >>
      - install_deps
      - show_node_version
      - run:
          name: Run tests
          command: npm test

  test-unix:
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    environment:
      MAVEN_VERSION: << parameters.maven_version >>
      JDK: << parameters.jdk_version >>
    steps:
      - checkout
      - install_sdkman
      - install_jdk_unix:
          jdk_version: << parameters.jdk_version >>
      - install_maven_unix:
          maven_version: << parameters.maven_version >>
      - install_deps
      - show_node_version
      - run:
          name: Run tests
          command: npm test

  release:
    <<: *defaults
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - install_deps
      - run: sudo npm i -g semantic-release @semantic-release/exec pkg
      - run:
          name: Publish to GitHub
          command: semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
    - lint:
        name: Lint
        context: nodejs-install
        node_version: "lts"
        filters:
          branches:
            ignore:
              - master

    # UNIX tests
    - test-unix:
        name: Unix Tests for Maven=3.6.1 JDK=10 Node=8
        context: nodejs-install
        maven_version: "3.6.1"
        jdk_version: "10"
        node_version: "8"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-unix:
        name: Unix Tests for Maven=3.6.1 JDK=11 Node=10
        context: nodejs-install
        maven_version: "3.6.1"
        jdk_version: "11"
        node_version: "10"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-unix:
        name: Unix Tests for Maven=3.6.1 JDK=11 Node=12
        context: nodejs-install
        maven_version: "3.6.1"
        jdk_version: "11"
        node_version: "12"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-unix:
        name: Unix Tests for Maven=3.3.9 JDK=8 Node=12
        context: nodejs-install
        maven_version: "3.3.9"
        jdk_version: "8"
        node_version: "12"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-unix:
        name: Unix Tests for Maven=3.3.9 JDK=9 Node=12
        context: nodejs-install
        maven_version: "3.3.9"
        jdk_version: "9"
        node_version: "12"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-unix:
        name: Unix Tests for Maven=3.3.9 JDK=10 Node=12
        context: nodejs-install
        maven_version: "3.3.9"
        jdk_version: "10"
        node_version: "12"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-unix:
        name: Unix Tests for Maven=3.3.9 JDK=11 Node=12
        context: nodejs-install
        maven_version: "3.3.9"
        jdk_version: "11"
        node_version: "12"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-unix:
        name: Unix Tests for Maven=3.3.9 JDK=12 Node=12
        context: nodejs-install
        maven_version: "3.3.9"
        jdk_version: "12"
        node_version: "12"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-unix:
        name: Unix Tests for Maven=3.3.9 JDK=13 Node=12
        context: nodejs-install
        maven_version: "3.3.9"
        jdk_version: "13"
        node_version: "12"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-unix:
        name: Unix Tests for Maven=3.6.1 JDK=8 Node=12
        context: nodejs-install
        maven_version: "3.6.1"
        jdk_version: "8"
        node_version: "12"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-unix:
        name: Unix Tests for Maven=3.6.1 JDK=12 Node=12
        context: nodejs-install
        maven_version: "3.6.1"
        jdk_version: "12"
        node_version: "12"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-unix:
        name: Unix Tests for Maven=3.6.1 JDK=11 Node=12
        context: nodejs-install
        maven_version: "3.6.1"
        jdk_version: "11"
        node_version: "12"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master

    # Windows tests
    - test-windows:
        name: Windows Tests for Maven=3.6.1 Node=8
        context: nodejs-install
        maven_version: "3.6.1"
        node_version: "8.17.0"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-windows:
        name: Windows Tests for Maven=3.6.1 Node=10
        context: nodejs-install
        maven_version: "3.6.1"
        node_version: "10.21.0"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-windows:
        name: Windows Tests for Maven=3.6.1 Node=12
        context: nodejs-install
        maven_version: "3.6.1"
        node_version: "12.0.0"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-windows:
        name: Windows Tests for Maven=3.3.9 Node=12
        context: nodejs-install
        maven_version: "3.3.9.2"
        node_version: "12.0.0"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master

    # Release
    - release:
        name: Release
        context: nodejs-app-release
        node_version: "10"
        filters:
          branches:
            only:
              - master
